events {}

http {
    server {
        listen 443 ssl;

        ssl_certificate     /app/cert.pem;
        ssl_certificate_key /app/key.pem;

        location / {
            proxy_pass http://vpn-runner:29000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 29000;

        location / {
            proxy_pass http://vpn-runner:29000;
        }
    }
}